ALTER TABLE inventory DROP COLUMN IF EXISTS warehouse_id CASCADE;

DROP TABLE IF EXISTS warehouse_transactions CASCADE;
DROP TABLE IF EXISTS "WAREHOUSE_TRANSACTIONS" CASCADE;
DROP TABLE IF EXISTS purchase_order_lines CASCADE;
DROP TABLE IF EXISTS purchase_orders CASCADE;
DROP TABLE IF EXISTS "PURCHASE_ORDERS" CASCADE;
DROP TABLE IF EXISTS suppliers CASCADE;
DROP TABLE IF EXISTS "SUPPLIERS" CASCADE;
DROP TABLE IF EXISTS warehouses CASCADE;
DROP TABLE IF EXISTS "WAREHOUSES" CASCADE;
